### ISSUE TITLE
Performance Team Meeting #1

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#1]
This is going to be the new home of the @nodejs/performance team. Thank you for all your warm messages and interest towards making Node.js faster. Feel free to create issues about things you care about and ask feedback on the current task you're working.

I created a poll for the first meeting of the performance team. The agenda will be determined in the following days, but for now I appreciate if people planning to attend the first meeting comments on this issue, and fills the poll on Doodle.

Poll: https://doodle.com/meeting/participate/id/bq7M01pe

**Comment by AVVS** [comment]
Would love to be on the team :)

**Comment by mcollina** [comment]
I won't be able to attend additional meetings. However here is a goal: make `fetch` fast https://github.com/nodejs/undici/issues/1203. This also means making WHATWG Streams fast.

@RafaelGSS can likely fill you in.

**Comment by sheplu** [comment]
I think one of the choice was today for the kickoff. Can you display / reveal when should be held this first meeting @anonrig  ?

**Comment by anonrig** [comment]
I opened a meeting issue @sheplu: https://github.com/nodejs/performance/issues/7
