### ISSUE TITLE
Rewrite getPackageScopeConfig in C++

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#123]
Writing it will reduce C++ to JS calls. 

Ref: https://github.com/nodejs/node/blob/main/lib/internal/modules/esm/package_config.js

**Comment by H4ad** [comment]
I think the overhead of sending the JS Object from C++ will be higher than the benefits from it.

**Comment by RafaelGSS** [comment]
@anonrig can you link to the PR that addresses it? just for record.

**Comment by anonrig** [comment]
> @anonrig can you link to the PR that addresses it? just for record.

Sure thing. It's implemented in https://github.com/nodejs/node/commit/ab171ba7876fa96ff8d3a247fc02c1e2785fb0d3
