### ISSUE TITLE
nodejs-bench-operations comparison between v20 and v21

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/performance#133]
I recently ran all the nodejs-bench-operations suite and apparently, Node.js 21 contains some operations significantly faster than Node.js 20.

See: https://twitter.com/_rafaelgss/status/1722213930188312667

I've created the issue just for visibility, maybe we can use this + the whole nodejs-benchmark suite as a metric on every major release (and even non-major releases).

**Comment by anonrig** [comment]
Amazing work @RafaelGSS!
