### ISSUE TITLE
Reducing Buffer.from(str, ENC_1).toString(ENC_2) usage across Node

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#16]
There are lots of `Buffer.from(value, ENC).toString(ENC_2)` code duplication in Node. I recommend creating a C++ function to do the same execution with less JS/C++ calls. `bufferToString(value, encoding_1, encoding_2);` that returns a string.

For example:
- buffer.js - btoa - `Buffer.from(input, 'latin1').toString('base64');`
- buffer.js - atob - `Buffer.from(input, 'base64').toString('latin1')`
- _http_client.js - `Buffer.from(options.auth).toString('base64')`
- random.js - `Buffer.from(arrayBuffer).toString('hex')`

**Comment by aduh95** [comment]
> * random.js - `Buffer.from(arrayBuffer).toString('hex')`

We could probably have a JS-only method that does that without going through the `Buffer` API at all, which may or may not be faster than a C++ implementation.

<details>

```js
function numberToHexCharCode(number) {
  return (number < 10 ? 49 : 97) + number;
}

/**
 * @param {ArrayBuffer} buf {}
 */
function arrayBufferToHexString(buf) {
  const length = buf.byteLength;
  const chars = Array(length * 2);
  const view = new DataView(buf);

  for (let i = 0; i < length; i++) {
    const val = view.getUint8(i);
    chars[2 * i] = numberToHexCharCode(val >> 4);
    chars[2 * i + 1] = numberToHexCharCode(val & 0xf);
  }

  return Reflect.apply(String.fromCharCode, null, chars);
}
```

</details>

> * buffer.js - btoa - `Buffer.from(input, 'latin1').toString('base64');`
> * buffer.js - atob - `Buffer.from(input, 'base64').toString('latin1')`

Given we recommend against using those functions, I'm not sure we should worry about the perf of those at all.

**Comment by anonrig** [comment]
@aduh95 Would you like to open a pull request for the 'hex' example you provided, or should I?

**Comment by aduh95** [comment]
I haven’t run any benchmark to validate if it’s actually faster – but I guess I could open the PR anyway and run the benchmark on Jenkins. Le 21 nov. 2022 à 20:07, Yagiz Nizipli ***@***.***> a écrit :﻿
@aduh95 Would you like to open a pull request for the 'hex' example you provided, or should I?

**Comment by anonrig** [comment]
I've looked into a couple of places, but this issue is not applicable anymore. I'm closing it. In case there are any objections, please re-open it. Thanks.
