### ISSUE TITLE
node:crypto performance for working with JWT

### ISSUE THREAD

**Issue by pasha-vuiko** [nodejs/performance#179]
Hello! First of all I wanted to say thank you for the awesome job you do here, you really make the Node.js better!

I noticed, that Node.js has very poor performance in such a common operation as working with JWT in comparison with other languages:

https://medium.com/deno-the-complete-reference/node-js-vs-python-whos-faster-for-jwt-sign-verify-efd249eaba39
https://medium.com/deno-the-complete-reference/node-js-vs-java-how-faster-is-bytecode-compared-to-interpreted-code-for-jwt-sign-verify-910caa55a7f2

The same situations in comparison with other JS runtimes:

https://medium.com/deno-the-complete-reference/node-js-vs-deno-whos-faster-for-jwt-sign-verify-1015169d8c02
https://medium.com/deno-the-complete-reference/node-js-vs-bun-whos-faster-for-jwt-sign-verify-78cd47dd06ca

So I guess if other JS runtimes are much faster in this, I guess it is possible to make big improvements for node:crypto a lot as well, because for example usage of Rust binding with https://github.com/napi-rs/node-rs/tree/main/packages%2Fjsonwebtoken makes it 3+ times faster, so it definitely something wrong with node:crypto here.

I'm sorry I can't introduce some PR to help, because I'm not a C/C++ guy 😔.

I hope you will be able to take your attention to the issue, as working with JWT is a very common task, and it would be great if it worked better.

**Comment by RafaelGSS** [comment]
Hi, 

We won't take libraries into consideration (example `jsonwebtoken`), but for `node:crypto`, we have identified that OpenSSL 3.0.x is slower than OpenSSL 1.1.1 (used by Node.js <= 16.x). See: https://github.com/nodejs/performance/issues/72

**Comment by pasha-vuiko** [comment]
Wow, really big performance drop, looks like it might be the cause of the issue. I'll try OpenSSL 1.1.1 for an experiment. Thank you!

**Comment by RafaelGSS** [comment]
Closing in favor of #72
