### ISSUE TITLE
Merging Github team with README

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#19]
Currently, there are 18 members at @nodejs/performance Github team. I'd like to sync the Github team information with the README in order to understand the interested parties and keep the team up to date.

Please open a pull request to the performance repository if you are interested in joining the discussions and meetings.

**Comment by tniessen** [comment]
Shouldn't everyone in the team then be listed on the readme? I'm not quite sure what the purpose of doing this is (this team is neither recognized as a Working Group nor as a Strategic Initiative as far as I an tell), but I assume nobody joined the new performance team without wanting to participate.

**Comment by mcollina** [comment]
I think there is an automated tool to do this.

**Comment by mcollina** [comment]
(I do not have time to add more meetings to my calendar. However, I'm happy to partecipate).

I don't think you should kick people out of a team if they didn't send a PR to update a README.

**Comment by anonrig** [comment]
> Shouldn't everyone in the team then be listed on the readme? I'm not quite sure what the purpose of doing this is (this team is neither recognized as a Working Group nor as a Strategic Initiative as far as I an tell), but I assume nobody joined the new performance team without wanting to participate.

@tniessen It is better to discuss this in-depth in the meeting, but my purpose is to keep track of who has access to `performance` repository, as well as, know who to ask for any feedback in case of a performance issue risen. Right now, 90% of the GitHub performance team is dormant.

> I don't think you should kick people out of a team if they didn't send a PR to update a README.

@mcollina The first question I have in  mind is: How can we track membership, and `performance` repo permission, if the performance team is not equal to the GitHub team? I don't think you need to attend meetings to be a part of this team, but it's good to know who we can ask for feedback (and maybe, in the future, assign people with their expertise in the corresponding node sub-system.)

**Comment by Trott** [comment]
> I think there is an automated tool to do this. @Trott or @mhdawson might know?

[`ncu-team`](https://github.com/nodejs/node-core-utils/blob/main/docs/ncu-team.md) can be used to automate it.

**Comment by mcollina** [comment]
Github teams are a way to receive notifications.

I'm -1 in removing people from this github team for this specific reason.

**Comment by anonrig** [comment]
I deleted my comment, due to not selecting the correct words to describe my motivation. Let's discuss this in the meeting tomorrow.
