### ISSUE TITLE
Do not parse numbers on url parsers - ipv4 

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#36]
[`EndsInNumber`](https://github.com/nodejs/node/blob/main/src/node_url.cc#L430) parses the number, but does not use the result of it. Just using the validations, without the parsing, would make ipv4 parsing 28% faster.

Similar comparison is: https://github.com/ada-url/ada/pull/36

**Comment by debadree25** [comment]
So basically instead of `int64_t num = ParseIPv4Number(last_str, last_str + last.size());` we would just use a validator here?

**Comment by debadree25** [comment]
Understood! Thanks! will attempt this!

**Comment by miguelteixeiraa** [comment]
I'm really sorry @debadree25 ! : ((
I was already working on it and should have commented something here.
I apologize for that

**Comment by debadree25** [comment]
> I'm really sorry @debadree25 ! : (( I was already working on it and should have commented something here. I apologize for that

No issue at all checking out your PR to learn!!
