### ISSUE TITLE
Change zoom meeting types

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#42]
Unfortunately, zoom meetings does not have the ability to live stream, and due to this we can't live stream the performance meetings. We need to change the meeting type to a webinar (I'm not quite sure), and update all the meeting scripts to use and post the new URL.

cc @mhdawson Can you help with this?

**Comment by mhdawson** [comment]
@anonrig I think we got you access to zoom? From there you can create a webinar. Once you have the new zoom link, then updating for meeting scrips is a PR to https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/meeting_base_performance
