### ISSUE TITLE
AbortSignal pattern is slow

### ISSUE THREAD

**Issue by ronag** [nodejs/performance#44]
To the point that e.g. RxJS has decided not support it.

https://github.com/ReactiveX/rxjs/pull/6675#event-8318057582

- [AbortError creation is slow](https://github.com/nodejs/node/pull/46648)
- Event creation is slow
- [Register/Unregister is slow](https://github.com/nodejs/performance/issues/60)

**Comment by anonrig** [comment]
What can we do in this area? Any suggestions? @jasnell @mcollina

**Comment by jasnell** [comment]
this was recently addressed. The change may not have been fully backported tho? Not sure.

**Comment by anonrig** [comment]
> this was recently addressed. The change may not have been fully backported tho? Not sure.

Which particular pull request are you referring to?

**Comment by jasnell** [comment]
#44048 looks like it was backported to 18.x in #44941 tho

**Comment by ronag** [comment]
@jasnell do you mean the transferable fix? I think abort signals are still slow but now it's because of eventtarget.

**Comment by ronag** [comment]
@benjamingr

**Comment by jasnell** [comment]
Interesting ok. Well, I guess we need to figure out how to speed up EventTarget now. That said, really none of the Web Platform standard apis were designed with performance as a high priority. We'll have to keep find ways of optimizing while still remaining compliant to the specs.

**Comment by santigimeno** [comment]
@jasnell any thoughts on [this](https://github.com/nodejs/performance/issues/32#issuecomment-1420529685) and specially on the `Event.isTarget` property? Thanks!

**Comment by benjamingr** [comment]
> @benjamingr

@ronag I'm reading this, I think EventTarget can be made faster (discussion in that thread + a few other ideas).

As for RxJS's case, we can also fast-path `util.aborted` now that we have that. Basically when a user calls it we don't go through the addEventListener machinery and go through parallel machinery avoiding it.

**Comment by anonrig** [comment]
Referencing: https://github.com/nodejs/node/pull/46648

**Comment by benjamingr** [comment]
So - just to elaborate a little on RxJS's case. Us fixing EventTarget wouldn't help them at all since it would still be slow in the browser which they also support.

Their avoidance isn't because our implementation is slow.

**Comment by anonrig** [comment]
Closing since it's a duplicate.
