### ISSUE TITLE
Performance regression Date.toISOString()

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/performance#47]
These are the last results of `nodejs-bench-operations`

- v18 - https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#date-toisostring
- v19 - https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v19.md#date-toisostring

and as you can see, toISOString might have been affected by a regression.

**Comment by RafaelGSS** [comment]
And it seems to be there since v19.3.0 (at least) https://github.com/RafaelGSS/nodejs-bench-operations/tree/main/v19.

**Comment by anonrig** [comment]
We updated to V8 10.8 in v19.3.0. Could this be related?

[[c8421204b0](https://github.com/nodejs/node/commit/c8421204b0)] - deps: patch V8 to 10.8.168.21 (Michaël Zasso) https://github.com/nodejs/node/pull/45749

**Comment by RafaelGSS** [comment]
No. This was caused by a semver-major change. I've adjusted the repository to run the benchmark against 18.0.0 and 19.0.0 and the regression is still there.

- v19.0.0 https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/v19/RESULTS-v19_0_0.md#date-toisostring
- v18.0.0 https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/v18/RESULTS-v18_0_0.md#date-toisostring

**Comment by targos** [comment]
It's probably the update to V8 10.7

**Comment by targos** [comment]
Implementation of toISOString was changed in https://github.com/v8/v8/commit/126d4779256509a492671bba8bdc440916a9f89a

**Comment by anonrig** [comment]
Is there an open issue in the V8 bug tracker for this?

**Comment by targos** [comment]
probably not

**Comment by anonrig** [comment]
Is the regression still there with V8 11.3? @RafaelGSS

**Comment by ronag** [comment]
I don't think this is actionable?

**Comment by RafaelGSS** [comment]
Yeah, it's more a tracking issue in case someone wants to fix it in the upstream.
