### ISSUE TITLE
getLibuvNow is slow

### ISSUE THREAD

**Issue by ronag** [nodejs/performance#49]
![Screenshot 2023-02-03 at 20 32 40](https://user-images.githubusercontent.com/3065230/216759596-a9af7910-cf0d-4985-a48e-e107b918c5fb.png)

Affects timers performance. I think it could be optimised with v8 fast calls. Profile is from undici.

**Comment by tony-go** [comment]
It will be the moment to test the documentation shipped by @anonrig 🤩

**Comment by anonrig** [comment]
How can we get the environment from a fast API? Referencing:

```
  Environment* env = Environment::GetCurrent(args);
```

**Comment by anonrig** [comment]
Keeping this issue as it is, until @joyeecheung's pull request is merged.

**Comment by anonrig** [comment]
We can close this issue, since the PR is merged.
