### ISSUE TITLE
Session proposals for the next Collaborator Summit - what should we submit

### ISSUE THREAD

**Issue by sheplu** [nodejs/performance#64]
Base issue to discuss if we want to meet there and dedicate some time to talk about specific topics or any other ideas. Could be interesting to prepare that in advance :) 

Some global ideas:
- web stream performances
- benchmark ci/cd
- HTTP (including parser, ada...)

[Link to issue](https://github.com/openjs-foundation/summit/issues)

**Comment by anonrig** [comment]
I think all 3 of those issues you've recommended should be at least discussed in the summit. I'll be happy to share more knowledge on Ada.
