### ISSUE TITLE
Buffer.byteLength and simdutf

### ISSUE THREAD

**Issue by ronag** [nodejs/performance#66]
`Buffer.byteLength` can be implemented more efficiently with simdutf

**Comment by ronag** [comment]
I don't understand. The following code should be able to use simdutf without any additional copying?

https://github.com/joyeecheung/node/blob/ee1ce1872ff38fc5a2fd3b2e3a97600e5d6b2e14/src/node_buffer.cc#L798-L808

**Comment by joyeecheung** [comment]
That's only hit in the case where the string is known to be one-byte and sequential (on the premise that fast API calls are hit).
