### ISSUE TITLE
Node.js Performance Team Meeting 2022-11-14

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#7]
## Time

13:00 EDT 14-Nov-2022 (01:OO PM)

Or in your local time:
- https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Performance+Team&iso=20221114T13&p1=179
- https://www.wolframalpha.com/input?i=01PM+EDT%2C+Nov+14%2C+2022+in+local+time

## Links

- Minutes Google Doc: https://docs.google.com/document/d/1SOth1yjmhOUN6zSWT7b613c4o3ajcnLhxQWloO9Kuf0/edit

## Agenda

- https://github.com/nodejs/performance/issues/8
- https://github.com/nodejs/performance/issues/2
- https://github.com/nodejs/performance/issues/4
- https://github.com/nodejs/performance/issues/6
- https://github.com/nodejs/performance/issues/5
- https://github.com/nodejs/node/issues/45389

## Joining the meeting

Zoom link: https://zoom.us/j/99289045212

## Invitees

Please use the following emoji reactions in this post to indicate your
availability.

👍 - Attending
👎 - Not attending
😕 - Not sure yet

**Comment by sheplu** [comment]
I will be there !

**Comment by RafaelGSS** [comment]
The Node.js Project is inviting you to a scheduled Zoom meeting.

Topic: Node.js Performance working group meeting
Time: Nov 14, 2022 03:00 PM Sao Paulo

Join Zoom Meeting
https://zoom.us/j/99289045212

Meeting ID: 992 8904 5212
One tap mobile
+13126266799,,99289045212# US (Chicago)
+13462487799,,99289045212# US (Houston)

Dial by your location
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 360 209 5623 US
        +1 386 347 5053 US
        +1 507 473 4847 US
        +1 564 217 2000 US
        +1 646 558 8656 US (New York)
        +1 646 931 3860 US
        +1 669 444 9171 US
        +1 669 900 6833 US (San Jose)
        +1 689 278 1000 US
        +1 719 359 4580 US
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 309 205 3325 US
        855 880 1246 US Toll-free
        877 369 0926 US Toll-free
        +1 204 272 7920 Canada
        +1 438 809 7799 Canada
        +1 587 328 1099 Canada
        +1 647 374 4685 Canada
        +1 647 558 0588 Canada
        +1 778 907 2071 Canada
        +1 780 666 0144 Canada
        855 703 8985 Canada Toll-free
Meeting ID: 992 8904 5212
Find your local number: https://zoom.us/u/a6HCZ4eEC

**Comment by UlisesGascon** [comment]
I will be there too :)

**Comment by sheplu** [comment]
WIth the replay available on youtube I will watch it quickly and review the minutes to PR the document today @anonrig
