### ISSUE TITLE
Governance & Meeting Schedule

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#8]
Even though performance team is not a working group, I'd like to have a open discussion about the governance model and the meeting schedule.

**Comment by sheplu** [comment]
Following the first meeting of the team, it seems that the current / voted schedule is something that is working for everyone (at least the people being present :D )

Monday 6pm UTC time every two weeks. 

Depending on the people who would like to attend - it could be harder for people in Asia as this would be later / middle of the night - we could see and maybe update in the futur to alternate between two schedules
