### ISSUE TITLE
Expensive `isTraceHTTPEnable`

### ISSUE THREAD

**Issue by H4ad** [nodejs/performance#81]
## Problem

I was doing some performance analysis on my lib and I found the following trace:

![nodejs-18 x](https://github.com/nodejs/performance/assets/12551007/99b0ac53-9b59-47e5-854a-ea3fe36232d5)

The method [isTraceHTTPEnable](https://github.com/search?q=repo%3Anodejs/node%20isTraceHTTPEnabled&type=code) is consuming 58ms to check if the trace is enabled when I process 100k requests with total time of ~7s.

To check if tracing is enabled, this method calls a method inside `internalBinding('trace_events')` to return a boolean, so this slowdown is likely caused by data being passed from the C++ layer to JavaScript.

## Reproduction

You can reproduce this CPU Profile and learn how to visualize [in this repo](https://github.com/H4ad/nodejs-trace-http-performance-analysis).

## Solutions

The first solution I thought of was to use v8 Fast APIs, I don't know much about that, but from what I've read in the docs, since the return value is just a boolean, I think it's eligible to be used.

I also thought about caching these values but that won't work since the user can enable and disable tracing whenever he wants, as per [the documentation](https://nodejs.org/api/tracing.html)

If you think is possible to use v8 Fast APIs, I can try to work on a PR.

**Comment by ronag** [comment]
@nodejs/performance @nodejs/http

**Comment by ronag** [comment]
I don't know if I'd consider it **that** expensive. But yea, that could be faster.

**Comment by mcollina** [comment]
This can be cached/hoisted easily in jsland. It would be a good PR.

Good finding @ronag!

**Comment by bnoordhuis** [comment]
> This can be cached/hoisted easily in jsland (by patching the enable function)

That's probably not sound in general. For example, an embedder can enable the `node.http` trace category directly through V8's C++ API.

W.r.t. V8's fast API: isTraceCategoryEnabled() and trace() are already V8 builtins. There's probably not much room for improvement there.

What should work is expose the uint8_t pointer from `platform->GetTracingController()->GetCategoryGroupEnabled("node.http")` as a single-element Uint8Array and change `isTraceHTTPEnabled()` to:
```js
function isTraceHTTPEnabled() {
  return array[0] > 0; // where |array| is that Uint8Array
}
```
