### ISSUE TITLE
Nominate @H4ad to nodejs/performance team

### ISSUE THREAD

**Issue by anonrig** [nodejs/performance#86]
We don't have any official nomination process for being a part of performance team, but I'd like to share my gratitude and officially welcome @H4ad to @nodejs/performance team.

@H4ad appreciate it if you can add your name to the repository README

**Comment by UlisesGascon** [comment]
+1 Super welcome @H4ad! 🙌

![](https://media.giphy.com/media/Ztfno2Qtm2dVxS81f5/giphy.gif)

**Comment by H4ad** [comment]
Opened https://github.com/nodejs/performance/pull/88!

Thank you all, @anonrig and also @RafaelGSS, you have inspired and helped me all this time, I am very happy to be able to contribute and be part of this team.

I also want to thank @marvinhagemeister, your first blog post on how to speedup JS ecosystem inspired me to learn more about performance and contribute to open source libraries, so keep doing this work, this work certainly inspires a lot of people as well inspired me.
